language: rust
rust: nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
notifications:
  email: false
  webhooks:
    - https://webhooks.gitter.im/e/bfbe44e3428e06f96c90
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
